In [1]:
import pandas as pd

In [2]:
pop=pd.read_csv('./flot_pop_18_19_20_rere.csv', encoding='ansi')

In [3]:
pop.rename(columns={'기준_년_코드':'year','구':'gu', '총_유동인구_수':'pop'},inplace=True)

In [4]:
pop.drop(columns=['2020_총_유동인구_수_평균(상권코드)', '2019_총_유동인구_수_평균(상권코드)',
       '2018_총_유동인구_수_평균(상권코드)','기준_분기_코드', '상권_코드', '상권_코드_명'], inplace=True)

In [5]:
pop.head(1)

year  id   gu      pop
0  2020  18  송파구  9692443

In [6]:
import numpy as np

In [7]:
def outliers_iqr(data):
    q1, q3 = np.percentile(data,[2,75])
    iqr = q3 - q1
    lower_bound = q1 - (iqr * 1.5)
    upper_bound = q3 + (iqr * 1.5)
    
    return np.where((data > upper_bound)| (data < lower_bound))

In [8]:
pop_2020_1=pop[(pop['year']==2020) & (pop['gu']=='서대문구')]

In [9]:
delete_pop=outliers_iqr(pop_2020_1['pop'])[0]

In [10]:
delete_pop

array([ 13,  18,  77,  82, 141, 146, 205, 210], dtype=int64)

In [11]:
pops = pd.DataFrame()

In [12]:
re = pd.DataFrame(columns=['index','gap'])
for ye in set(pop['year']):
    for i in set(pop['id']):
        a = pop[(pop['year']==ye) & (pop['id']==i)]['pop']
#         print(outliers_iqr(a))
        if len(outliers_iqr(a)[0]) != 0:
            re1=pop.loc[(outliers_iqr(a)[0]),'pop']
            for i in re1.index:
                for s in re1.values:
#                 print(re1.values)
#                 print(re1.values[i])
                    re = re.append(pd.DataFrame([[i, s]],
                                        columns=['index','gap']), ignore_index= True)
#             s=list(a)
            

In [13]:
re.to_csv('./rest.csv',encoding='ansi')

### restart

In [15]:
pop_re = pd.read_csv('./self_test_pop.csv', encoding='ansi')

In [16]:
pop_re.columns

Index(['id', 'year', 'id_gu', 'gu', 'pop'], dtype='object')

In [19]:
re = pd.DataFrame(columns=['index','gap'])
listex=[]
for ye in set(pop_re['year']):
    for i in set(pop_re['id_gu']):
        a = pop_re[(pop_re['year']==ye) & (pop_re['id_gu']==i)]['pop']
        if len(outliers_iqr(a)[0]) != 0:
            re1=pop_re.loc[(outliers_iqr(a)[0]),'pop']
            print(re1.index)
            
            listex=re1.append(listex)
            print(listex.values)

Int64Index([42, 45, 99, 102, 111, 156], dtype='int64')
[6155512 5093640 2788286 2293309 3537164 4548182]
Int64Index([58, 94, 130], dtype='int64')
[4943172 3689705 3897951 6155512 5093640 2788286 2293309 3537164 4548182]
Int64Index([18], dtype='int64')
[6274310 4943172 3689705 3897951 6155512 5093640 2788286 2293309 3537164
 4548182]
Int64Index([27], dtype='int64')
[8668736 6274310 4943172 3689705 3897951 6155512 5093640 2788286 2293309
 3537164 4548182]
Int64Index([46, 94, 142, 190], dtype='int64')
[3910370 3689705 5013914 6112939 8668736 6274310 4943172 3689705 3897951
 6155512 5093640 2788286 2293309 3537164 4548182]
Int64Index([6, 13, 18, 52, 53, 70, 77, 82, 116, 117, 141, 146, 180, 181, 244,
            245],
           dtype='int64')
[10638967  3999803  6274310  4323620  4148942  5543774  3849639   949507
  4041107  4083361  3916261  3245872  4577563  6092344  4778064  3517018
  3910370  3689705  5013914  6112939  8668736  6274310  4943172  3689705
  3897951  6155512  5093640  278

In [ ]:
re = pd.DataFrame(columns=['index','gap'])
listex=[]
for ye in set(pop_re['year']):
    for i in set(pop_re['id_gu']):
#         print(ye)
        a = pop_re[(pop_re['year']==ye) & (pop_re['id_gu']==i)]['pop']
        if len(outliers_iqr(a)[0]) != 0:
            re1=pop_re.loc[(outliers_iqr(a)[0]),'pop']
            print(re1.index)
#             print(re1)
#             pop_re.drop(pop_re.values[re1.values], axis=0, inplace=True)
#             for i in re1.index:
#                 for s in re1.values:
#                     re = re.append(pd.DataFrame([[i, s]],
#                                         columns=['index','gap']), ignore_index= True)
            listex=re1.append(listex)
            print(listex.values)

In [21]:
listex

4      5812854
9      9787553
14     3832525
19     8487732
54     5702012
        ...   
45     5093640
99     2788286
102    2293309
111    3537164
156    4548182
Name: pop, Length: 79, dtype: int64

In [22]:
pop_re

id  year  id_gu   gu      pop
0          1  2020     18  송파구  9692443
1          2  2020      2  강동구  8798709
2          3  2020      2  강동구  7345107
3          4  2020      2  강동구  1425329
4          5  2020      2  강동구  5812854
...      ...   ...    ...  ...      ...
12115  12116  2018     23  종로구    52333
12116  12117  2018     23  종로구  1400238
12117  12118  2018     23  종로구  1747636
12118  12119  2018     23  종로구  2304441
12119  12120  2018     23  종로구   590419

[12120 rows x 5 columns]

In [ ]:
for i in range(len(rmDatas[0])):
    if rmDatas[0][i].is
    rmDatas[0].dropna(axis=0)

In [ ]:
rmDatas[0]

In [ ]:
pop.index[1].drop()

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
import seaborn as sns

In [ ]:
import numpy as np

In [ ]:
fig=plt.figure(figsize=(10,6))
sns.boxplot(data=pop_2020_1)

In [ ]:
type(delete_pop)

In [ ]:
pop_2020_1.iloc[[13,18,  77,  82, 141, 146, 205, 210],3]#,  ]

In [ ]:
a=pop[(pop['year']==2020) & (pop['id']==1)]

In [ ]:
a= outliers_iqr(pop[(pop['year']==2020) & (pop['id']==1)]['pop'])

In [ ]:
a[0]

In [ ]:
pop[pop['year']==2020].index

In [ ]:
# i=[]
for i in pop['id']:
#     print(i)
    globals()['pop' + str(i)] = i
#     print(pop1 + pop2)
# test2

In [ ]:
# import pymysql.cursors # Connect to the database

# connection = pymysql.connect(host='localhost',
#         user='root',
#         password='1234',
#         db='classicmodels',
#         charset='utf8',
#         cursorclass=pymysql.cursors.DictCursor)